ORG_SUFFIXES = [
    "Inc", "Corp", "LLC", "Ltd", "Company", "Co", "Co.", "PLC", "S.A.", "G.m.b.H", "GmbH",
    "Assurances", "Group", "Bank", "Commission", "Ministry", "Department", "Dept",
    "Committee", "Board", "Exchange", "Trust", "Administration", "Court", "FDA",
    "Party", "Senate", "Congress", "Association", "Organization", "Org", "Theater",
    "Laboratories", "Management", "Holdings", "Partnership", "Service", "Services",
    "Systems", "Insurance", "Securities", "Capital", "Investment", "Farm", "Farms",
    "Stores", "Industry", "Industries", "Mfg", "Credit", "Electric", "Motor",
    "Communications", "Entertainment", "Network", "Networks", "Channel", "Office",
    "Reserve", "Treasury", "League", "Review", "Corporation", "Agency", "Institution",
    "Bureau", "Authority", "Council", "Institute", "Foundation", "Society", "Union",
    "Federation", "Confederation", "Alliance", "Coalition", "University", "College",
    "School", "Academy", "Museum", "Center", "Centre", "Hall", "Rep", "Theatre",
    "Creditbank", "AS", "G.m.b", "H", "N.A.", "S&L", "S&Ls", "TV", "NBC", "ABC", "CBS",
    "CIA", "FBI", "IRS", "FDA", "SEC", "FHA", "VA", "GAO", "GATT", "NASD", "RTC",
    "ULI", "MIT", "UCLA", "HBO", "MTV", "VH", "NASA", "NATO", "UN", "U.N."
]
ORG_KEYWORDS = [
    "Federal", "National", "International", "American", "European", "World",
    "United", "Royal", "State", "Central", "General", "Standard", "Professional",
    "Agricultural", "Financial", "Industrial", "Commercial", "Corporate", "Business",
    "Municipal", "Regional", "Local", "Urban", "Metropolitan", "Capital",
    "Supreme", "Foreign", "Domestic", "Public", "Private", "Government",
    "Chamber", "House", "White", "Pentagon", "Treasury", "Justice", "Commerce",
    "Defense", "Energy", "Education", "Health", "Transportation", "Agriculture",
    "Labor", "Veterans", "Security", "Intelligence", "Budget", "Small", "Credit",
    "New", "Old", "City", "County", "Town", "Port", "Hill", "Lake", "Park",
    "Square", "Street", "Avenue", "Road", "Place", "Court", "Plaza", "Building",
    "Tower", "Center", "Mall", "Market", "Store", "Shop", "Gallery", "Studio",
    "Theatre", "Cinema", "Hotel", "Restaurant", "Bank", "Hospital", "Clinic",
    "School", "College", "University", "Academy", "Library", "Museum", "Theater",
    "Stadium", "Arena", "Field", "Pool", "Gymnasium", "Auditorium", "Hall",
    "Room", "Office", "Suite", "Floor", "Complex", "Plaza",
    "UN", "CNN", "CIA", "FBI", "Fed", "IBM", "NBC", "CBS", "Journal", "Pepsi",
    "GE", "PLO", "FHA", "FDIC", "GAO", "GATT", "NASD", "RTC", "ULI", "MIT",
    "UCLA", "HBO", "MTV", "NASA", "NATO", "U.N.", "CBI", "CDU", "TDK", "UAL",
    "IRS", "S&P", "NU", "LDP", "RIT",
    "Sony", "Ford", "GM", "Chrysler", "Toyota", "Nissan", "Volvo", "Cadillac",
    "Pontiac", "Polaroid", "Revlon", "Forbes", "Chevrolet", "Dodge", "Acura",
    "Sterling", "Hyundai", "Lexus", "Renault", "Fiat", "Isuzu", "Daihatsu",
    "Mitsubishi", "Merkur", "Mercedes", "Caterpillar", "Aetna", "Allianz",
    "Pan", "Apple", "Intel", "Compaq", "Sun", "AST", "Tandy", "Advanced",
    "Digital", "Hewlett", "LSI", "AST",
    "Times", "Post", "Economist", "News", "Review", "Literary"
]


COUNTRIES = ["japan", "germany", "france", "italy", "china", "canada", "mexico",
             "brazil", "india", "australia", "russia", "spain", "poland", "israel",
             "egypt", "korea", "switzerland", "sweden", "norway", "finland",
             "ireland", "portugal", "greece", "turkey", "iran", "iraq", "syria",
             "lebanon", "jordan", "saudi", "oman", "kuwait", "qatar", "uae",
             "pakistan", "afghanistan", "thailand", "vietnam", "malaysia",
             "indonesia", "philippines", "argentina", "chile", "peru", "cuba",
             "venezuela", "colombia", "ecuador", "bolivia", "paraguay", "uruguay",
             "hungary", "romania", "bulgaria", "czech", "slovakia", "austria",
             "belgium", "netherlands", "denmark", "morocco", 'united', "algeria", "tunisia",
             "libya", "sudan", "ethiopia", "kenya", "nigeria", "ghana", "angola",
             "zimbabwe", "zambia", "mozambique", "madagascar", "namibia", "botswana"]

CITIES = ["london", "paris", "tokyo", "moscow", "beijing", "berlin", "rome",
          "madrid", "sydney", "toronto", "mumbai", "delhi", "cairo", "rio",
          "jakarta", "bangkok", "seoul", "istanbul", "lagos", "buenos aires",
          "kinshasa", "karachi", "shanghai", "manila", "dhaka", "miami",
          "chicago", "houston", "phoenix", "philadelphia", "san antonio",
          "san diego", "dallas", "san jose", "austin", "jacksonville",
          "fort worth", "columbus", "charlotte", "indianapolis", "san francisco",
          "seattle", "denver", "washington", "boston", "detroit", "nashville",
          "memphis", "portland", "oklahoma city", "las vegas", "baltimore",
          "louisville", "milwaukee", "albuquerque", "tucson", "fresno",
          "sacramento", "kansas city", "long beach", "mesa", "atlanta",
          "virginia beach", "omaha", "colorado springs", "raleigh", "miami",
          "oakland", "minneapolis", "tulsa", "wichita", "new orleans",
          "arlington", "cleveland", "bakersfield", "anaheim", "honolulu",
          "tampa", "aurora", "santa ana", "st. louis", "pittsburgh",
          "cincinnati", "riverside", "lexington", "anchorage", "stockton",
          "toledo", "st. paul", "newark", "greensboro", "buffalo", "plano",
          "lincoln", "henderson", "fort wayne", "jersey city", "st. petersburg",
          "chula vista", "norfolk", "orlando", "chandler", "laredo", "madison",
          "durham", "lubbock", "winston-salem", "garland", "glendale",
          "hialeah", "reno", "baton rouge", "irvine", "chesapeake", "irving",
          "scottsdale", "north las vegas", "fremont", "gilbert", "san bernardino",
          "boise", "birmingham"]

STATES_USA = ["california", "texas", "florida", "new york", "pennsylvania", "illinois",
              "ohio", "georgia", "north carolina", "michigan", "new jersey", "virginia",
              "washington", "arizona", "massachusetts", "tennessee", "indiana", "missouri",
              "maryland", "wisconsin", "colorado", "minnesota", "south carolina", "alabama",
              "louisiana", "kentucky", "oregon", "oklahoma", "connecticut", "iowa",
              "mississippi", "arkansas", "kansas", "utah", "nevada", "new mexico",
              "west virginia", "nebraska", "idaho", "hawaii", "maine", "new hampshire",
              "rhode island", "montana", "delaware", "south dakota", "north dakota",
              "alaska", "vermont", "wyoming"]
